### ISSUE TITLE
hardware used ?

### ISSUE THREAD

**Issue by ghost** [shamblett/iot-home#1]
hey @shamblett. I am am architect ( the building type ) and messing around with IOT.
What hardware are you using for the python code ?
I presume the hardware is running python, not dart and communicating over mqtt ?

**Comment by shamblett** [comment]
The hardware is a beagle bone green running debian, with Dart installed on it with the mqtt_client package, the python scripts are there to bridge the Dart VM to the onboard sensors, full read [here ](https://medium.com/@stevehamblett/dart-in-the-iot-world-a-practical-example-601f036212c7)

**Comment by ghost** [comment]
Thanks Steve.

I think I am trying to build a hydroponics system. Totally out of my depth.
Mqtt is clearly the way to go with dart.
But for communication I am using golang Periph project from Google so I
don't need any scripting languages. Mentioning this as it might be good for
you.

I will study the link !

**Comment by shamblett** [comment]
If your using go you don't need Dart, you should be able to do everything in go.
