### ISSUE TITLE
JWT token is invalid.

### ISSUE THREAD

**Issue by ricksondpenha** [shamblett/iot-home#2]
Hi, is there any way we can generate a JWT token with ES256 based signing, google iot only supports RSA256 & ES256 based keys. I've tried implementing a JWT library from Jose but have a issue there eith ES256 based signing. 

[https://github.com/appsup-dart/jose/issues/1#issuecomment-470838614](url)

**Comment by shamblett** [comment]
Yes I fell into a bit of  a trap here, when I updated from Dart 1.0 to Dart 2.0 the JWT library I was using wasn't ready, it depended on pointycastle I think which itself wasn't ready so I updated the code to use what was there for Dart 2.0. I've not looked at this for a while but the only libraries you have(unless your own) are those in pub. I need to revisit this to see where we are.

**Comment by ricksondpenha** [comment]
I'm using the jose plugin for now.. but even that seems to be not working for some reason, and the maintainer of the repository isn't replying for any issues for now. Can you look at the jose library and may be try it out:
[https://github.com/appsup-dart/jose](https://github.com/appsup-dart/jose)

**Comment by shamblett** [comment]
Yes Ok I'll have a look at this.
